### ISSUE TITLE
Outputs not retrieved from long history of deployments

### ISSUE THREAD

**Issue by vincebowdren** [keesschollaart81/vsts-arm-outputs#129]
Issue: If a resource group has a deployment history with lots (hundreds) of deployments, it's **not** possible to use a filter to get outputs from a deployment way back in the history; the task fails with an error "Deployment could not be found for Resource Group".

Version: keesschollaart.arm-outputs.arm-outputs.ARM Outputs@5, called from either an Azure Devops release pipeline or a YAML pipeline.

Steps to reproduce:

1. Prepare a resource group with a history of many hundreds of differently named deployments; the history needs to be long enough such that the [Azure Rest API listing deployments](https://docs.microsoft.com/en-us/rest/api/resources/deployments/listbyresourcegroup) cannot return all the deployments in a single response (cf [docs on paging](https://docs.microsoft.com/en-us/rest/api/azure/#async-operations-throttling-and-paging)). I think that the precise number will vary, depending on the amount of data in each deployment record; in our case the number was 391.
2. Construct a deploymentNameFilter string which does _not_ match any of the deployments returned in the API's first page of results, but _does_ match one or more older deployments. For example, use the exact name of one of the older deployments.
3. run the task with the selected deploymentNameFilter

Expected result:
The task retrieves the outputs from the historic deployment
Actual result:
The task fails with an error: "Deployment could not be found for Resource Group"

Notes: it might be possible to work around the paging problem by applying filters (deploymentNameFilter and provisioningState) in the API call, instead of filtering the records after retrieving them?

**Comment by keesschollaart81** [comment]
Confirmed. Just pushed a fix! Thanks for the bug report, sorry for the delay ;-)
