### ISSUE TITLE
Feature Request : Offline Arm-Output parsing

### ISSUE THREAD

**Issue by Bjego** [keesschollaart81/vsts-arm-outputs#130]
Hey, your Azure Devops Plugin looks promising.

But I think you should add an offline parsing feature. The ARM-Deploymenttask can generate a string variable within the pipeline. It should be easy to skip all the API querying/calls and just parse the json-string to the desired variables.

See the property "deploymentOutputs" of the documentation: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops

It's a json string stored in a variable. 

Kind regards

**Comment by karpikpl** [comment]
I used script like this:
```powershell
#Requires -Version 3.0
<##################################
# Title: Parses output from deployment and sets environment variables in the release pipeline
# Author: Piotr Karpala
# Description:  
# Inputs: 
	 unnamed arguments - output of ARM template execution in JSON format 

###################################>
Param(
)

for ( $i = 0; $i -lt $args.count; $i++ ) {
    
	# convert to object
	$obj = $args[$i] | convertfrom-json

	foreach($object_properties in $obj.PsObject.Properties)
	{
		# display for debug
		# Write-Output "Key: [$($object_properties.Name)]: [$($object_properties.Value.value)]"
		 Write-Output "setting key: [$($object_properties.Name)]"

		# set Azure DevOps variables
		echo "##vso[task.setvariable variable=$($object_properties.Name)]$($object_properties.Value.value)"
	}
} 
```

I need to name the outputs from my deployment and pass it into this script
