### ISSUE TITLE
Using Filter Deployment Name

### ISSUE THREAD

**Issue by KZeronimo** [keesschollaart81/vsts-arm-outputs#22]
Hi - I've been using this task to successfully capture ARM outputs - I decided to "test" the filter deployment (I really don't have concurrent ARM deployments going on in the same rg - I do have some nested templates and the remaining ARM deployments are sequential so I have a capture ARM outputs after each deploy ARM step) - I used the name of my template file ie `foo.json` I entered `foo` in the Filter Deployment Name - I ran two successful deployments and both time I encountered the following

<img width="1003" alt="screen shot 2019-02-03 at 5 02 05 pm" src="https://user-images.githubusercontent.com/21271446/52183426-d8c7c980-27d5-11e9-82cf-5479de52165d.png">

Any idea what I'm doing incorrectly?

Thanks in advance

**Comment by keesschollaart81** [comment]
Maybe. This is a breaking change between v4 and v5. In the most recent version of ARM Outputs I use [micromatch](https://github.com/micromatch/micromatch) as the matching algoritm so you need to use * for wildcard searches or an exact match (case insensitive). I've updated the info-tooltip with this info. Does this fix your issue?
