### ISSUE TITLE
Task v5 fails if there is no output

### ISSUE THREAD

**Issue by cnoureau** [keesschollaart81/vsts-arm-outputs#25]
Hi,

I am using v4 version of this task and it works great.

I tried to upgrade to v5 but got an error "No output parameters could be found for the deployment".

It seems to be a regression because it was working well since version 2.x (cf https://github.com/keesschollaart81/vsts-arm-outputs/issues/4)

**Comment by keesschollaart81** [comment]
Correct. I've just fixed this, will roll out later this week after some QA testing

**Comment by keesschollaart81** [comment]
This is now available in v5.2!
