### ISSUE TITLE
Deployment Name Filter

### ISSUE THREAD

**Issue by Leo-Mepham** [keesschollaart81/vsts-arm-outputs#7]
I have a problem where I have concurrent deployments going to the same resource group. This means the last deployment to that resource group when I get it may not be the one I want for the pipeline I am in, meaning variables do not have the values I want.

I plan to add an optional "deployment name" filter, which users would enter as the filename of the deployment they want the latest outputs for. If this is empty, the task behaves as it does now. If this is populated it will filter the deployments and get the latest that matches the filter.

I'll pop in a PR when done, you can merge in if you think it's generally useful.

**Comment by keesschollaart81** [comment]
Yes, that sounds useful!

**Comment by Leo-Mepham** [comment]
Great stuff, popped in a PR :)

**Comment by keesschollaart81** [comment]
Thanks. Will do a review and some testing tomorrow or early next week 👌

**Comment by keesschollaart81** [comment]
Merged your PR, tested, published to marketplace as v3.0! Thanks!
